name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install linter
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.2
      - name: Run linter
        run: golangci-lint run --config .golangci.yml